// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 8a3f07cf872521ba1cfafaa9ed7f9bdf39ceaf303a761c4ec2541b1ae9888c2a

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "jaccount-keycloak-theme";

export const themeNames: ThemeName[] = ["jaccount-keycloak-theme"];

export type KcEnvName =
    | "ORGS_SIDECAR_SERVER_URL"
    | "SHADCN_THEME_LAYOUT"
    | "SHADCN_THEME_APP_NAME";

export const kcEnvNames: KcEnvName[] = [
    "ORGS_SIDECAR_SERVER_URL",
    "SHADCN_THEME_LAYOUT",
    "SHADCN_THEME_APP_NAME"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ORGS_SIDECAR_SERVER_URL: "http://localhost:3000",
    SHADCN_THEME_LAYOUT: "centered-card",
    SHADCN_THEME_APP_NAME: "jAccount"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                    case "account":
                        return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
