// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 75d4fb2fac0e6d41432e636e87a5a198ad837a62ccb248e53b8ab3a4885a5ae7

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "jaccount-keycloak-theme";

export const themeNames: ThemeName[] = ["jaccount-keycloak-theme"];

export type KcEnvName =
    | "ORGS_SIDECAR_SERVER_URL"
    | "SHADCN_THEME_LAYOUT"
    | "SHADCN_THEME_APP_NAME"
    | "SHADCN_THEME_BASE"
    | "SHADCN_THEME_PRESET"
    | "SHADCN_THEME_SIDE_IMAGE_URL"
    | "SHADCN_THEME_FONT"
    | "SHADCN_THEME_RADIUS"
    | "SHADCN_THEME_PLACEHOLDER"
    | "SHADCN_THEME_LOGO_WHITE_URL"
    | "SHADCN_THEME_LOGO_DARK_URL";

export const kcEnvNames: KcEnvName[] = [
    "ORGS_SIDECAR_SERVER_URL",
    "SHADCN_THEME_LAYOUT",
    "SHADCN_THEME_APP_NAME",
    "SHADCN_THEME_BASE",
    "SHADCN_THEME_PRESET",
    "SHADCN_THEME_SIDE_IMAGE_URL",
    "SHADCN_THEME_FONT",
    "SHADCN_THEME_RADIUS",
    "SHADCN_THEME_PLACEHOLDER",
    "SHADCN_THEME_LOGO_WHITE_URL",
    "SHADCN_THEME_LOGO_DARK_URL"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ORGS_SIDECAR_SERVER_URL: "http://localhost:3000",
    SHADCN_THEME_LAYOUT: "centered-card",
    SHADCN_THEME_APP_NAME: "jAccount",
    SHADCN_THEME_BASE: "neutral",
    SHADCN_THEME_PRESET: "lime",
    SHADCN_THEME_SIDE_IMAGE_URL: "",
    SHADCN_THEME_FONT: "montserrat",
    SHADCN_THEME_RADIUS: "normal",
    SHADCN_THEME_PLACEHOLDER: "true",
    SHADCN_THEME_LOGO_WHITE_URL: "",
    SHADCN_THEME_LOGO_DARK_URL: ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                    case "account":
                        return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
